services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - migrate

  db:
    image: postgres:14-bullseye
    env_file:
      - .env
      - .env.sample
    environment:
      - DB_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ums"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
  migrate:
      image: migrate/migrate:latest
      volumes:
        - ./migrations:/migrations
      command:
        ["-path", "/migrations", "-database", "postgres://postgres:password@db:5432/ums?sslmode=disable", "up"]
      depends_on:
        db:
          condition: service_healthy
